version: '3.8'

services:
  opnsense:
    image: demisto/opnsense:1.0.0.3547071
    container_name: opnsense-dev
    restart: on-failure
    platform: linux/amd64  # Specify the platform for Apple Silicon compatibility
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      wan:
        ipv4_address: 192.168.100.1
      lan:
        ipv4_address: 192.168.1.1
      management:
        ipv4_address: 192.168.2.1
    ports:
      # Web UI ports
      - "8443:443"   # HTTPS Web UI
      - "8080:80"     # HTTP Web UI (redirects to HTTPS)
      # SSH access
      - "2222:22"     # SSH
    volumes:
      - ./conf:/conf  # Configuration storage
      - ./etc:/etc    # System files
      - ./var:/var    # Variable data
    environment:
      - TZ=America/New_York  # Set your timezone

networks:
  wan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
    driver_opts:
      com.docker.network.bridge.name: br-wan
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
    driver_opts:
      com.docker.network.bridge.name: br-lan
  management:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
    driver_opts:
      com.docker.network.bridge.name: br-mgmt
